######################################################################
##
## Filename: conware.udo
## Created on: Mon May 01 4:11:46 PM Central Daylight Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
